export const artistDescriptions: Record<string, string> = {
  "Guiding Youth":
    "Guiding youth is a new sound in Ghent with a passion for roots reggae, poetry, message and old school (80s) equipment. With my sound I am trying to help my family and people back in Chile.",
  "Selah Techniques":
    "Selah Techniques is about bringing the message of Peace, Love and Unity through Reggae Music to the people. From their onset in 2003, they've been spreading crowd-rocking vibes with solid foundation tunes. Consisting of a vinyl freak and a conscious rudeboy, the members of Selah Techniques have been involved in the Belgian underground music scene since the late nineties. MC Deeds spent those days organizing politically radical squat bashments through the infamous Smart Art Movement, while selector Stubborn was inspired to start crate-digging by the likes of Unlisted Fanatic(s) and veteran selector Sugar Charly.\n\nSelector Stubborn, the vinyl freak from Selah Techniques, has been collecting and spinning Reggae 45's for years and years. Stubborn used to live in Berlin (2005-2006) where he had a weekly slot at the famous YAAM Club; he also runs Caoutchou Records (a Ghent electronica imprint) and is their resident DJ as for Double Cup (a footwork jungle rave party concept). Nowadays he is hosting Roots Reggae Club Night (a 2-monthly club night at Kinky Star - Gent).",
  "Selah Techniques ft. Della":
    "Selah Techniques is about bringing the message of Peace, Love and Unity through Reggae Music to the people. From their onset in 2003, they've been spreading crowd-rocking vibes with solid foundation tunes. Consisting of a vinyl freak and a conscious rudeboy, the members of Selah Techniques have been involved in the Belgian underground music scene since the late nineties.\n\nSelector Stubborn, the vinyl freak from Selah Techniques, has been collecting and spinning Reggae 45's for years and years.",
  Della:
    "Fakka 't is hier Della, aka de BARMOEDER. Je kent me van achter de bar in de Minus One, Vierde Zaal, 't Pand en andere Gentse dubjes. Achter de schermen MC ik een beetje, en respect is the message, alleen voor wie het verdient tho want soso lobi is die movement. DELLA coming trough, tijd om te skanken!",
  "Creativ Dubs":
    "Creativ Dubs is Belgian soundsystem collective, spreading the message since 2018. Mosi, Tz'unun and Mr. S3p love to dig in their vinyl collection and also present you some own productions. From foundation roots music to the more experimental dubs with an organic and 'creative touch'. The message of freedom & unification will always be their central focus. Straight from the heart to the people.\n\nSlowly but steadily they are expanding their borders, making connections all around and inviting artists from near and far while organizing reggae record markets in Ghent together with Poa Annua and the Grassroots Movement.",
  "Break Bread":
    "Break Bread Soundsystem is an Antwerp based sound founded by Jamie and Oscar, later joined by Luka and Dimi. Rooted in a strong sense of brotherhood, the name reflects the bond that connects us, based on sharing, caring and coming together through music and culture.\n\nDriven by a deep passion for roots, reggae, dub and soundsystem culture, we have a combined collection that spans from soulful roots to heavy steppers, allowing us to create a selection for almost any occasion.\n\nFor us, it is more than just playing music. It is about creating a connection and building a place where people can freely express and enjoy themselves while sharing something meaningful with the people in front of the speakers.",
  "Break Bread Soundsystem":
    "Break Bread Soundsystem is an Antwerp based sound founded by Jamie and Oscar, later joined by Luka and Dimi. Rooted in a strong sense of brotherhood, the name reflects the bond that connects us, based on sharing, caring and coming together through music and culture.\n\nDriven by a deep passion for roots, reggae, dub and soundsystem culture, we have a combined collection that spans from soulful roots to heavy steppers, allowing us to create a selection for almost any occasion.\n\nFor us, it is more than just playing music. It is about creating a connection and building a place where people can freely express and enjoy themselves while sharing something meaningful with the people in front of the speakers.",
  "Ital Brew":
    "Sounds by Ital Brew focuses on the foundation of modern sound system culture, consciousness and respect. The stage for genres such as rocksteady, ska, blue beat, soul, Jamaican rhythm & blues, early roots. The founders of the scene as we know it today are becoming increasingly scarce and Ital Brew wants to change that.",
  "Little Man":
    "Little Man is a soundsystem founded in the north of Belgium, but currently based in Ghent. The first boxes were built in 2018, with little knowledge of soundsystem culture but big curiosity. Since then, the crew, collection, knowledge, and sound have grown, and now the time has come to organise something bigger!",
  "Dreadical Warriors":
    "Hailing from Ghent, Dreadical Warriors are known for their militant selection and deep, spiritual vibes of roots & dub culture in Belgium. With their full custom-built sound system and a foundation built on resistance and upliftment, expect full pressure, rare dubplates, and soundsystem music in its rawest form.",
  "Steppin' Ground ft. Ras TimBo":
    "Steppin' Ground Soundsystem is a Dutch collective of five dub lovers and reggae enthusiasts, based in Arnhem. Since a little over two years, their system has been carefully designed to transfer basslines and melancholic rhythms to resonate with the hearts of those who dance in front of it. From roots reggae to heavy steppers, and with hints of soul and jungle, the collective is steadily building their desired wall of music, speaker for speaker.\n\nRas TimBo, the self-proclaimed Gypsy-Dread, is convincing over 15 years with his constant, likeable and charismatic nature and likes to play with his different voices across roots, reggae, dub, steppas, digital, hiphop and dancehall.",
  "Jahmateur Hi Power":
    "Jahmateur Hi Power was founded in Ghent back in 2015. What started with first sound experiences and learning the ropes grew into a real mission guided by love for the music, the message and the sound system traditions.\n\nThe name Jahmateur comes from amateur, not as in unskilled, but as in a lover of Jah music. In 2023 they got the chance to revive King Earthquake Sound, a true UK legend.",
  "Bloodhound ft. MC Kingten":
    "Founded in 2017, Bloodhound soundsystem is a rising Antwerp-based soundsystem. Inspired by pioneers such as Lee Perry, King Earthquake, Iration Steppas and King Alpha, they bring raw heavyweight sessions full of energy and passion.\n\nSince 2018, Kingten has grown into the recognizable voice and resident MC of Bloodhound Soundsystem. What began as a spontaneous jump on the mic evolved into a raw style where daily reality, hope and community are central.",
  Unification:
    "Unification Soundsystem has established itself as a significant entity in the Belgian reggae and soundsystem culture. Based in Ghent, they have been active for more than 20 years, hosting events and founding Vibes Kitchen vzw. Their sets are characterized by heartfelt roots and dub selections that create a welcoming atmosphere at every session.",
  "Fishermen ft. Wiseman Jarne":
    "FisherMen Soundsystem is a Ghent based crew that grew from love for roots reggae music and built a custom hand-built soundsystem. Since 2016 they host events and play a versatile mix between foundation roots and digital reggae, spreading heartfelt rhythms and meaningful messages.\n\nMC Wiseman Jarne started collecting in 2013 and developed an energetic and conscious MC style with strict lyric, no gimmick.",
  "Poa Annua":
    "Poa Annua brengt sinds 2017 een unieke selectie aan reggaemuziek, met stevige baslijnen en opzwepende melodieën. De vinylselectie richt zich op One Drop Rhythm, early Jamaican Roots en stevige Stepper cuts, aangevuld met huisgemaakte dubs.",
  Deliverance:
    "Deliverance Soundsystem is a Ghent based soundsystem founded in 2015, originally known as RDC Sound. They play pure roots & culture in a versatile style, from uplifting roots to rare digi and heavy dubplates. Roots & culture is the way, love is the key.",
  "UFO Collective (Unlisted Fanatic, MariJah & Moonshine Horns)":
    "2024 confirmed the UFO Collective as a diverse spaced out dub act. Playing a dozen of shows both on sound and stage, on occassions the UFO even landed not to play the warm up but to keep people dancing after main acts such as African Head Charge (404/Vooruit BE) and Groundation (Rastaplas NL). Couleur Cafe was the Collective's personal highlight with the whole crowd singing along to our version of Wadada spreading a message of love and understanding throughout CC's dubcorner. The UFO Collective is always on the move to apply new grooves and sounds to expand their Afro, Ethio and Jazz influenced Dub Universe. The UFO will take you on a musical journey through vast galaxy of heavy rhythms spiced up with live horns, synths and vocals.",
  "Crucial ft. MC Tubbie":
    "Crucial Soundsystem is run by two dedicated young warriors with a mission to bring change through conscious reggae and dub music. Rooted in faith, sound system culture and the guidance of Jah, they deliver music for mind, body and soul.\n\nMC Tubbie, original freestyle MC outta West Flanders, brings lyrical guidance with passion, preaching inclusion every step of the way!",
  "Suncharm ft. Crownless I":
    "Suncharmdub is een community uit Leuven waar vibes en losgaan centraal staan. Jonge selecta's en mc's spelen diverse sets met stem, instrumenten en percussie, aangevuld met zelf geproduceerde tracks.\n\nCrownless I is an Antwerp-based MC, singer, selecta and operator. His main intention is to provide a mindful message and a meditational vibration to unite people.",
  Lowie:
    "WAGWAN! Lowie is a up-and-coming selecta youth, deeply passionate about roots reggae music and focused on spreading conscious messages and heavy vibrations. Humble and driven by sound, with big respect for the foundation.",
  "Moksha Vibrations":
    "As Moksha Vibrations Soundsystem we strongly believe in the effects of music in a trance-state flow. We focus on bringing people together and unifying under uplifting music styles from roots and culture to deep dub pressure. Inclusivity and a safe space for expression through movement are central.\n\nMoksha stands for liberation from Samsara, and for this gathering of tribes you can expect rocksteady, Studio 1, deep roots, UK dub and dubplates.",
  Pathseeker:
    "Pathseeker Soundsystem, vier koppen. Sound with a mission, niet te stoppen. Higher meditation, steppas crew, love for the roots en een duidelijke drive naar unity. Veel liefde en lof voor de dub community.",
  Untzslag:
    "Untzslag is a hybrid soundsystem founded by young people from Ghent and Brussels with a passion for reggae, dub and tekno and deep love for soundsystem culture. Founded in 2024, they already hosted multiple parties and bring selections of roots, rockers, UK dub and heavy steppas.",
  "Saga Sound Station":
    "Saga Sound Station steps forward with vibration as our language. Founded in Ghent, we explore every corner of low-frequency culture from foundation roots to heavy experimental dub. No boundaries, only deep vibration, hypnotic rhythm and heavyweight energy.",
  Drijfkracht:
    "Drijfkracht is a heavyweight soundsystem outta Ghent, representing Rough Rhythm since 2019. Inspired by UK dub, Steppers, Rubadub and Digital, they focus on bringing a rough selection and creating a unique energetic vibe. MC Simon Says, Mr Maison Man and Sista Aischa drive the dance while the upgraded soundsystem provides deep pressure.",
  Tune: "Tune Soundsystem is planning to bring the ruckus. We love to get the groove going with our beloved roots tunes straight into the rockers. When the time is ripe and the crowd is hot Nate B will make you jump up on it with banging steppas and rough rhythms. Funny fact: Tune Soundsystem was once based in Sleidinge!",
  "MUDA @ Living Dub":
    "Het MUDA is een Evergemse school voor kunstsecundair onderwijs in muziek en dans, met opleidingen hedendaagse dans, klassieke muziek, jazz/pop, songwriting, productie en musical/muziektheater. Living Dub Festival wenst dit jaar de leerlingen van het MUDA mee te ondersteunen in die autonomie door hen de kans te geven op het festival op te treden. Het MUDA barst van jong talent en dat mag gezien worden!",
  Ventus:
    "Ventus ontstond in Evergem. Emma Demoor en Gonzalo Temmermans zijn de founders en leadzangers van de band. 'De Oh Wonder van België' werd al meermaals verteld en gelijk hebben ze, want dit Brits duo was de allereerste inspiratiebron. Ze brengen dreamy indie alternatieve pop met soms zelf een vleugje rock.\n\nIn september 2023 opende de band op het grootste podium van Gent, op het Sint-Pietersplein de Student Kick off. De AB, Bozart en Botanique zijn ook al afgevinkt. Bij hun EP-release in 2023 was de Charlatan volledig uitverkocht!",
  Paleo:
    "Paleo is a producer and rapper from Ertvelde. Bringing you a special sound and good vibes all the time.",
  Mitch:
    "M1TCH, based in Sleidinge, has seemingly created his own religion of rap. Going along with this New HipHop Wave doesn't mean the lyrics don't have to mean nothing. Metaphors, calmly delivered punchlines and absurd humor is accompanied by heavy 808's, aggressive synths, guitars and more.\n\nThroughout the years M1TCH has been given the amazing opportunities to play at the likes of De Warmste Week, Viernulvier in Ghent, Charlatan, De Centrale, BRONKS in Brussels and much more.",
  "DJ Dédé":
    "DJ DÉDÉ (Dene Moring) is een Belgische DJ uit Sleidinge, actief binnen melodic house & techno en bekend om zijn sterke connectie met het publiek. Zijn sound is verrassend en meeslepend. Elke set draait om flow, emotie en het juiste spanningsmoment.\n\nIn 2025 werd DJ DÉDÉ uitgeroepen tot winnaar van Topradio, een belangrijke erkenning die zijn groei en impact binnen de Belgische elektronische scene onderstreept.",
  "DJ Ceductive":
    "DJ Ceductive is een allround DJ uit Evergem die moeiteloos verschillende genres door elkaar mixt en zo elke set uniek maakt. Met een scherp oor voor zijn publiek voelt hij perfect aan wat de dansvloer nodig heeft en stuurt hij de vibe waar die moet zijn. Van verrassende crossovers tot opbouwende energie: niets ligt vast, alles beweegt.",
  "MC Wiseman Jarne":
    "MC Wiseman Jarne started collecting his first records in 2013. After a few years he started to play warm-ups near his hometown Avelgem and Kortrijk. In 2016 he met his partner in dub, Stevie. Together they created the dub collective WiseMen. As Stevie was operator and producer of the WiseMen tunes, Jarne focused on selecting and taking care of the microphone business. This slowly evolved from spoken word in between tunes in the beginning days, to his own lyrics. Highly influenced by Belgian foundation MCs like Rudy Roots and Missing Link.\n\nJarne his MC style can be described as energetic and conscious, taking the values and standards of reggae music very serious. Jarne knows the world we are living in today and likes to share awareness through his lyrics. Lately, JaJarne is often seen with Fishermen during their sessions. Also for Living Dub, they combine forces to share a conscious and energetic vibe among the people. MC Wiseman Jarne comes to Living Dub with strictly lyric, no gimmick!",
  Danman:
    "Claston Brooks, stage name Danman aka Sunny Voice, is a veteran musician and singer who has covered the music scene on a local, regional, national and international basis for over 20 years. Born in St. Elizabeth, Jamaica, he migrated to the UK in 1967 at the age of 11. The first stop in the UK for the young artist was London, where he lived and attended Slay Brook High School in Harlesden for four years before moving to Huddersfield and finishing school at Fartown High. Danman played bongo drums for revival church in Jamaica during his childhood and is no newcomer when it comes to music.\n\nIt was in 1995 that he got his first experience in a recording studio. After enquiring about an advertisement, he was given the opportunity to record two of his own tracks free of charge at the Hudawi Centre in Huddersfield. One of those songs placed him third in a talent competition held at the Deighton Centre in 1995.\n\nIration Steppas Sound System was the next adventure for Danman and this led to the release of his first 10-inch vinyl, Too Much War.\n\nIn recent years Danman has worked closely with producer, label and sound system Indica Dubs. Together Danman and Indica have toured worldwide and produced heavyweight releases including the sought-after When Jah Come and Righteous Man, as well as exclusive dubplates such as Satta Massagana and many more.",
  "Ras Timbo":
    "Ras TimBo, the self-proclaimed Gypsy-Dread, has been convincing for over 15 years with his constant, likeable and charismatic nature. He likes to play with his different voices, which he uses across roots, reggae, dub, steppas, digital, hiphop and dancehall.\n\nBorn in Germany with North Macedonian roots, Ras TimBo has served as singer and MC for many bands, DJ constellations and soundsystems in over 10 countries. With his conscious lyrics, both written and freestyle, he proves that interaction with the massive while performing is important and possible.\n\nHis two vinyl releases are already sold out, and he continues to bring his energy live with Steppin' Ground Soundsystem.",
  Sotabosc:
    "Sotabosc is a self-managed music project from Barcelona that brings together local musicians to create art that critically engages with the capitalist system. Our goal is to imagine and share another possible world: a world where nature becomes again our habitat rather than a source of resources, and where solidarity and mutual aid are the center of human interactions. Reggae music inna Catalan Style!",
  "Not Surrender":
    "Since 2015, Timothy, Rami and Phong started regularly attending soundsystem-sessions in Beljam. Experiencing the culture, the vibe, and the impressive soundgear, these 3 good friends were instantly enamored by the reggae-soundsystem scene and declared: 'one day, we will operate our own soundsystem.' Now, almost a decade later, Not Surrender is thrilled to present their soundsystem and musical journey to the people.",
  "Indica Dubs ft. Danman":
    "Sukh started listening to vinyl and attending Roots / Dub events at a young age and describes it as a life changing experience. Inspired by the energy, the spiritual upliftment and vibes within the Dub community, Sukh started producing his own tunes by the age of 17. With a clear goal of reaching 100 independent vinyl releases on his own label, Indica Dubs was founded in 2010 and was quickly played by various top sound systems such as Jah Shaka, Channel One, Entebbe, King Earthquake, Iration Steppas, and many more.\n\nClaston Brooks, stage name Danman aka Sunny Voice is a veteran musician and singer with over 20 years of experience. Born in St. Elizabeth, Jamaica, he migrated to the UK in 1967. Danman has been working closely with Indica Dubs, touring worldwide and producing some of the most heavyweight releases including the sought-after When Jah Come and Righteous Man.",
};

export const workshopDescriptions: Record<string, string> = {
  "Henna Workshop":
    "Wat is henna nu precies, hoelang blijven de tattoos staan en wat is het verschil tussen bruine en zwarte henna? Kom naar onze workshop henna tattoos en ontdek het zelf! We geven je de basisinfo mee en je gaat zelf aan de slag. Niet te missen!\n\nElluminé is gespecialiseerd in allround make-up en event entertainment in de ruime zin van het woord. We zorgen voor die extra fonkelingen in de ogen.",
  "Henna Tattoos":
    "De henna artiest tovert jouw handen om tot een kunstwerk. Er wordt enkel gewerkt met 100 % natuurlijke henna. Kom langs voor een henna tattoo en draag het festival nog dagen met je mee.\n\nElluminé is gespecialiseerd in allround make-up en event entertainment in de ruime zin van het woord.",
  "Living Art":
    "Heb je zin om je creatieve zelf naar boven te laten komen? Kom dan naar onze AMAZING-workshop, Living Art. Samen gaan we ontdekken wat Living Dub echt betekent! In deze workshop gaan we te werk met verschillende materialen en technieken om tot het diepste van je inspiratie te gaan.\n\nHeyy, wij zijn Léa en Loes. Twee creatievelingen die vorig jaar op Sint-Lucas zijn afgestudeerd. We tekenen en zijn graag met kunst bezig.",
  "Ecstatic Dance":
    "Tijdens dit uurtje vormen we de workshop tent om tot een feestje! Maar dit bouwen we traag op. We beginnen met een korte ademhalingsoefening, daarna gaan we over naar wat rustige muziek, de BPM's gaan traag maar zeker steeds meer omhoog tot we uitkomen bij een hoogtepunt. Verwacht je qua genres aan folk, chillhop, trance, goa en alles daar tussen in. Dans zoals jij dat wilt en laat je helemaal meegaan in de muziek!",
  "Fire show":
    "Deze vuurdans combineert rope-dart en poi in een duet van vuur en dans. Kom naar de Irie Knowledge Hut tussen 23u en middernacht op vrijdag 3 juli om gehypnotiseerd te worden door deze vurige flow op het ritme van de muziek en de nacht.\n\nWij zijn Levi en Lisa. Op het podium zijn we Solace en Azra, twee creatieve pyromanen en dubfanaten.",
  "Mindfulness & Meditatie (Patricia van Wegen)":
    "Het doel van meditatie is niet gedachtenloos zijn (want dat kan niet), maar om te observeren, zonder deel te nemen of te oordelen. Na een bewust 'aankom'-moment begeleid ik jullie door middel van aandacht, lichaam- en adembewustzijn naar innerlijke rust, helderheid en aanwezigheid.\n\nIk (Patricia van Wegen) heb een 4-jarige erkende opleiding genoten, ben lid van de yogafederatie en heb diverse bijscholingen gevolgd.",
  "Integrale Yoga (Patricia van Wegen)":
    "Integrale yoga ziet de mens als één geheel: lichaam, adem, geest en bewustzijn en zijn onlosmakelijk met elkaar verbonden. Het is geen doelgerichte, maar een zachte benadering van het lichaam en de adem waarbij je constant luistert en observeert wat de behoeftes zijn van jou in dit eigenste moment. Yoga is een filosofie en bewustzijnsweg en een bijzonder pad om te bewandelen. Filosofie in beweging.\n\nIk (Patricia van Wegen) heb een 4-jarige erkende opleiding genoten, ben lid van de yogafederatie en heb diverse bijscholingen gevolgd.",
  "Airbrush & Kindergrime (Elluminé)":
    "We laten uw kinderen met kindergrime veranderen in hun favoriete helden, dieren en fantasiewezens. Veilig, kleurrijk en een grote glimlach! Daarnaast bieden we dan ook onze tijdelijke airbrush tattoos aan, deze blijven ca. 3 dagen staan, zijn veilig voor de huid en geschikt voor alle leeftijden. Van stoere doodskoppen tot mooie bloemen, we hebben voor elks wat wils!\n\nElluminé is gespecialiseerd in allround make-up en event entertainment in de ruime zin van het woord.",
  "Roots and Colors: Graffiti Workshop (Jote & Elmo)":
    "Tijdens deze creatieve graffitiworkshop nemen Jote en Elmo je mee in de wereld van street art. Deelnemers ontdekken hoe ideeën vorm krijgen via letters, lijnen en kleur, en gaan zelf actief aan de slag met graffiti als expressiemiddel. De workshop focust op creativiteit, experiment en persoonlijke stijl. Ervaring is niet nodig, goesting wel.\n\nWij zijn Jote en Elmo, graffiti-artiesten met een sterke band met street culture en visuele expressie.",
  "Natural Shapes":
    "In deze workshop van een uur ga je samen met mij freestylen met ijzerdraad en touw. Je leert enkele eenvoudige technieken en basisknopen, zodat je snel mee bent en binnen het uur al iets moois kunt maken. We laten ons inspireren door de natuur en maken vormen zoals planten en bloemen, maar er is ook ruimte om insecten of dieren te creëren.\n\nHallo, ik ben Burak. Ik ben een creatieveling die graag decoratie en accessoires maakt met verschillende materialen.",
  "Performance by Rodkint (Elise Deryckere)":
    "Rodkints praktijk is theatraal en gelaagd, met een sterke aandacht voor symboliek, lichaam en emotionele resonantie. Haar werk nodigt de toeschouwer uit om niet alleen te kijken of te luisteren, maar om zich te verhouden tot wat schuurt, overstroomt of langzaam verdwijnt.\n\nElise Deryckere - Rodkint (geb. 1994) is een multidisciplinair kunstenaar wiens werk zich beweegt op het snijvlak van beeld, performance en geluid.",
  "Organic farming and human care (Vzw Gooikenshoeve)":
    "Vzw Gooikenshoeve zal jullie op Living Dub Festival komen uitleggen hoe het ook anders kan. Verwacht je aan een verhaal over een warme, menselijke zorg voor mentaal kwetsbare kinderen in verbintenis met duurzame, lokale bio-landbouw.\n\nVzw Gooikenshoeve is een zorgboerderij in Ertvelde, die een warm nest biedt voor jongeren tussen 16 en 25 jaar met psychische moeilijkheden.",
  "Needle felting (Studio Imela)":
    "Maak je eigen sleutelhanger uit wol met Studio Imela! In deze workshop leer je een sleutelhanger te maken met behulp van naaldvilten. Je leert alles over de materialen en de technieken die je zal gebruiken om een mooi werkje te kunnen maken. De workshop duurt 2 uurtjes en je gaat naar huis met een zelfgemaakte sleutelhanger!\n\nIk ben Yasmine van Studio Imela. Naaldvilten doe ik al heel lang dus het is heel fijn om anderen de kneepjes van het vak te leren en hopelijk vinden sommigen van jullie een hele nieuwe hobby.",
  "Fortune teller: free card reading (Jules Tingles)":
    "Wat fluistert er onder je ribben? Welke vraag tikt al een tijdje vanbinnen? Schuif aan. Jules Tingles legt de kaarten en luistert tussen de lijnen. Antwoorden over morgen? Misschien. Een onverwachte wending? Het zou kunnen. Een spiegel voor je ziel? Zeker. Even vertragen. Even kijken. En weer verder — met iets dat is blijven hangen.\n\nDe waarzegster die jullie grootste vraagstukken zal ophelderen is Jules Tingles. Zij is werkzaam binnen Elluminé, gespecialiseerd in allround make-up en event entertainment.",
};
